# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
a =np.array([[[11,12,13],[14,15,16],[17,18,19]]])
print(a)

[[[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [3]:
print("The Shape of Array is-")
print(a.shape)

The Shape of Array is-
(1, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
a=np.zeros([5,5])
print("Intial matrix")
print(a)

Intial matrix
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
a[1][0]=1
a[2][1]=2
a[3][2]=3
a[4][3]=4
print("Final matrix")
print(a)

Final matrix
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
a = np.zeros((8,8))
print("array is:")
print(a)

array is:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
# Checkboard pattern 
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [8]:
b= np.random.random((5,5))
print("The original 2D array : ")
print(b)


The original 2D array : 
[[0.77035918 0.01682751 0.26980828 0.42495944 0.52201903]
 [0.72580244 0.58634792 0.78900801 0.56772674 0.97216207]
 [0.80791655 0.05261863 0.27130165 0.36711574 0.254859  ]
 [0.45534471 0.45696189 0.47757263 0.32448615 0.37761854]
 [0.38013248 0.13092426 0.43391473 0.63307245 0.24862394]]


In [9]:
# Normalize 
bmax=b.max()
bmin=b.min()
b=(b-bmin)/(bmax-bmin)    # The formula for normalizatiom
print("After normalization:")
print(b)

After normalization:
[[0.78876208 0.         0.26480856 0.42721361 0.5288111 ]
 [0.74212214 0.59614761 0.80828282 0.57665582 1.        ]
 [0.82807539 0.03746449 0.26637176 0.36666551 0.24916035]
 [0.45901951 0.4607123  0.48228667 0.32204282 0.37765936]
 [0.38029084 0.1194312  0.4365876  0.64505668 0.24263378]]


# 5.  How to find common values between two arrays?

In [10]:
arr1=np.array([[11,21,30],[18,75,60]])
arr2=np.array([[18,11,20],[40,21,50]])
print(arr1)
print(arr2)

[[11 21 30]
 [18 75 60]]
[[18 11 20]
 [40 21 50]]


In [11]:
print(np.intersect1d(arr1,arr2))

[11 18 21]


In [12]:
a = np.array([11,2,13,4,18])
b = np.array([6,7,18,11,10])
for i in b:
    if i in a:
        print("The common value between two array : ", i)

The common value between two array :  18
The common value between two array :  11


# 6.How to get the dates of yesterday, today and tomorrow?

In [13]:
# For this problem we use the numpy datetime64() and timedelta64() from numpy
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)

today     = np.datetime64('today', 'D')
print("Today: ",today)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [14]:
A = np.random.randint(0,2,7)
print("First array:")
print(A)

B = np.random.randint(0,2,7)
print("Second array:")
print(B)

print("Test above two arrays are equal or not!")
array_equal = np.allclose(A, B)
print(array_equal)

First array:
[1 1 0 0 0 1 0]
Second array:
[1 0 1 0 0 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [15]:
x = np.random.random(10)
print("Original array:")
print(x)

Original array:
[0.54801782 0.16904007 0.83013471 0.34441    0.32588705 0.97886037
 0.65468488 0.11319071 0.03863896 0.54107053]


In [16]:
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Maximum value replaced by 0:
[0.54801782 0.16904007 0.83013471 0.34441    0.32588705 0.
 0.65468488 0.11319071 0.03863896 0.54107053]


# 9. How to print all the values of an array?

In [26]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((11,11))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [18]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(3,3)
print(X)

Original matrix:

[[0.71708757 0.93794973 0.14141109]
 [0.97295577 0.24382971 0.68937125]
 [0.56686896 0.60344121 0.50817889]]


In [19]:
print("\n Subtract the mean of each row of the said matrix:\n")
Y = X - X.mean()
print(Y)


 Subtract the mean of each row of the said matrix:

[[ 0.11918821  0.34005037 -0.45648826]
 [ 0.37505641 -0.35406964  0.0914719 ]
 [-0.03103039  0.00554186 -0.08972046]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [24]:
a = np.ones(20)
b = np.random.randint(0,len(a),30)
a += np.bincount(b, minlength=len(a))
print(a)

[2. 4. 4. 2. 3. 3. 2. 3. 2. 2. 3. 1. 1. 1. 1. 6. 2. 3. 2. 3.]


In [25]:
np.add.at(a, b, 1)
print(a)

[ 3.  7.  7.  3.  5.  5.  3.  5.  3.  3.  5.  1.  1.  1.  1. 11.  3.  5.
  3.  5.]


# 12.How to get the diagonal of a dot product?

In [23]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
x=np.diag(np.dot(A, B))
y=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",x)
print("diagonal of a dot product method 2 is....",y)

[[0.40725517 0.50705488 0.81587144 0.01583089 0.36634838]
 [0.54590123 0.12919018 0.84371695 0.17031258 0.65827802]
 [0.48834489 0.32967443 0.7736153  0.35362015 0.21613863]
 [0.18129419 0.73553862 0.37452788 0.94457554 0.20048115]
 [0.69744867 0.39230369 0.88877798 0.34820684 0.56640972]]
[[0.01801549 0.82014788 0.69811423 0.46035221 0.72674744]
 [0.41411648 0.4083714  0.32706866 0.03608155 0.8434022 ]
 [0.01498805 0.76266515 0.87004859 0.45017573 0.02386043]
 [0.91035117 0.36370876 0.35381952 0.02176051 0.98929342]
 [0.42028263 0.88855658 0.09400416 0.74650131 0.87859437]]
diagonal of a dot product method 1 is.... [0.39792654 1.79081227 1.26726523 0.44881581 1.70106859]
diagonal of a dot product method 2 is.... [0.39792654 1.79081227 1.26726523 0.44881581 1.70106859]


# 13.How to find the most frequent value in an array?

In [6]:
import numpy as np
x = np.random.randint(0, 7, 11)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[3 0 3 3 1 6 0 6 5 2 4]
Most frequent value in the above array:
3


# 14.How to get the n largest values of an array

In [2]:
import numpy as np
Z = np.arange(10)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

[5 6 7 8 9]


# 15.How to create a record array from a regular array?

In [5]:

import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['go','Goa','gone','gg'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'go', 12.2)
(2, 'Goa', 15.)
(3, 'gone', 20.)
